# explicitly defining variables from http://jekyllrb.com/docs/configuration/
github_path: "http://0.0.0.0:4000/"
#"http://0.0.0.0:4000/"  #for local dev
#"cs194-fma/"  #for github pages
#"" #for upload to eecs

images:
- title: Cathedral
  ref:  images/output/out_cathedral.jpg
  link: http://zzeleznick.github.io/cs194-fma/images/output/out_cathedral.jpg
  data:
  - size: "(1024, 390)"
    vector: "Green =  <2, -2>;  Red =   <6, -3>"
- title: Tobolsk
  ref:  images/output/out_tobolsk.jpg
  link: "http://zzeleznick.github.io/cs194-fma/images/output/out_tobolsk.jpg"
  data:
  - size: "(1024, 396)"
    vector: "Green =  <3, -4>;  Red =   <3, -7>"
- title: Nativity
  ref:  images/output/out_nativity.jpg
  link: http://zzeleznick.github.io/cs194-fma/images/output/out_nativity.jpg
  data:
  - size: "(1024, 395)"
    vector: "Green =  <1, -4>;  Red =   <0, -6>"
- title: Settlers
  ref:  images/output/out_settlers.jpg
  link: http://zzeleznick.github.io/cs194-fma/images/output/out_settlers.jpg
  data:
  - size: "(1024, 395)"
    vector: "Green = <0, 0>;  Red = <-1, 1>"
- title: Monastery
  ref:  images/output/out_monastery.jpg
  link: http://zzeleznick.github.io/cs194-fma/images/output/out_monastery.jpg
  data:
  - size: "(1024, 391)"
    vector: "Green = <2, -10>;  Red = <2, -11>"
- title: White-Balanced Monastery
  ref:  images/output/out_monastery.jpg
  link: http://zzeleznick.github.io/cs194-fma/images/output/out_monastery.jpg
  data:
  - size: "(1024, 391)[2]"
    vector: "Green = <2, -10>;  Red = <2, -11>"



# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
gems:      []

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

quiet:    false
defaults: []

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style