# explicitly defining variables from http://jekyllrb.com/docs/configuration/
github_path: "http://0.0.0.0:4000/"
#"http://0.0.0.0:4000/"  #for local dev
#"cs194-fma/"  #for github pages
#"" #for upload to eecs
eecs_path: http://inst.eecs.berkeley.edu/~cs194-26/fa15/hw/proj1/data/

p3_path: 'images/p3/'
p3_images:
- title: Grand Canyon Original
  alpha: 0
  ref: blurred_blurred_grand-canyon.jpg
- title: Grand Canyon Sharpened
  alpha: 2.8
  ref:  unsharp_4_2.828_blurred_blurred_grand-canyon.jpg
- title: Grand Canyon Sharpened
  alpha: 4.0
  ref:  unsharp_5_4.0_blurred_blurred_grand-canyon.jpg

p3_hybrid_images:
- title: Alpaca
  ref: Alpaca.jpg
- title: Alpaca Highpass
  ref: highpass_Alpaca.jpg
- title: Taypaca
  ref: final_Alpaca.jpg
- title: Taylor Lowpass
  ref: lowpass_Jacob-Black.jpg
- title: Taylor
  ref: Jacob-Black.jpg

- title: Caitlyn Jenner
  ref: Caitlyn-Jenner.jpg
- title: Caitlyn Jenner Highpass
  ref: highpass_Caitlyn-Jenner.jpg
- title: Caice Jenner
  ref: final_Caitlyn-Jenner.jpg
- title: Bruce Jenner Lowpass
  ref: lowpass_Bruce-Jenner.jpg
- title: Bruce Jenner
  ref: Bruce-Jenner.jpg


- title: Donald Trump
  ref: Trump-Point.jpg
- title: Donald Trump Highpass
  ref: highpass_Trump-Point.jpg
- title: Donald Trump
  ref: final_Trump-Point.jpg
- title: Donald Trump Lowpass
  ref: lowpass_Trump-Bite.jpg
- title: Donald Trump
  ref: Trump-Bite.jpg

p3_hybrid_fft:
- title: DT 1 FFT
  ref: 1-fftTrump-Bite.jpg
- title: DT Lowpass FFT
  ref: 1-fft-lowTrump-Bite.jpg
- title: DT 2 FFT
  ref: 2-fftTrump-Point.jpg
- title: DT 2 Highpass FFT
  ref: 2-fft-highTrump-Point.jpg


p3_stack_images:

- title: Albert-Monroe Gaussian
  val: 0
  ref: blur_0_Albert-Monroe.jpg
- title: Albert-Monroe Gaussian
  val: 2
  ref: blur_1_Albert-Monroe.jpg
- title: Albert-Monroe Gaussian
  val: 4
  ref: blur_2_Albert-Monroe.jpg
- title: Albert-Monroe Gaussian
  val: 8
  ref: blur_3_Albert-Monroe.jpg
- title: Albert-Monroe Gaussian
  val: 16
  ref: blur_4_Albert-Monroe.jpg

- title: Albert-Monroe Laplacian
  val: 0
  ref: high_0_Albert-Monroe.jpg
- title: Albert-Monroe Laplacian
  val: 2
  ref: high_1_Albert-Monroe.jpg
- title: Albert-Monroe Laplacian
  val: 4
  ref: high_2_Albert-Monroe.jpg
- title: Albert-Monroe Laplacian
  val: 8
  ref: high_3_Albert-Monroe.jpg
- title: Albert-Monroe Laplacian
  val: 16
  ref: high_4_Albert-Monroe.jpg


- title: Taypaca Gaussian
  val: 0
  ref: blur_0_final_Alpaca.jpg
- title: Taypaca Gaussian
  val: 2
  ref: blur_1_final_Alpaca.jpg
- title: Taypacaa Gaussian
  val: 4
  ref: blur_2_final_Alpaca.jpg
- title: Taypaca Gaussian
  val: 8
  ref: blur_3_final_Alpaca.jpg
- title: Taypaca Gaussian
  val: 16
  ref: blur_4_final_Alpaca.jpg

- title: Taypaca Laplacian
  val: 0
  ref: high_0_final_Alpaca.jpg
- title: Taypaca Laplacian
  val: 2
  ref: high_1_final_Alpaca.jpg
- title: Taypaca Laplacian
  val: 4
  ref: high_2_final_Alpaca.jpg
- title: Taypaca Laplacian
  val: 8
  ref: high_3_final_Alpaca.jpg
- title: Taypaca Laplacian
  val: 16
  ref: high_4_final_Alpaca.jpg

- title: Brain Gaussian
  val: 0
  ref: blur_0_Brain.jpg
- title: Brain Gaussian
  val: 2
  ref: blur_1_Brain.jpg
- title: Brain Gaussian
  val: 4
  ref: blur_2_Brain.jpg
- title: Brain Gaussian
  val: 8
  ref: blur_3_Brain.jpg
- title: Brain Gaussian
  val: 16
  ref: blur_4_Brain.jpg

- title: Brain Laplacian
  val: 0
  ref: high_0_Brain.jpg
- title: Brain Laplacian
  val: 2
  ref: high_1_Brain.jpg
- title: Brain Laplacian
  val: 4
  ref: high_2_Brain.jpg
- title: Brain Laplacian
  val: 8
  ref: high_3_Brain.jpg
- title: Brain Laplacian
  val: 16
  ref: high_4_Brain.jpg

- title: Lincoln Gaussian
  val: 0
  ref: blur_0_Lincoln.jpg
- title: Lincoln Gaussian
  val: 2
  ref: blur_1_Lincoln.jpg
- title: Lincoln Gaussian
  val: 4
  ref: blur_2_Lincoln.jpg
- title: Lincoln Gaussian
  val: 8
  ref: blur_3_Lincoln.jpg
- title: Lincoln Gaussian
  val: 16
  ref: blur_4_Lincoln.jpg

- title: Lincoln Laplacian
  val: 0
  ref: high_0_Lincoln.jpg
- title: Lincoln Laplacian
  val: 2
  ref: high_1_Lincoln.jpg
- title: Lincoln Laplacian
  val: 4
  ref: high_2_Lincoln.jpg
- title: Lincoln Laplacian
  val: 8
  ref: high_3_Lincoln.jpg
- title: Lincoln Laplacian
  val: 16
  ref: high_4_Lincoln.jpg


p3_mask_images:
- title: Beach
  ref: Beach.jpg
- title: Mask Pope
  ref: Mask-Pope.jpg
- title: Pope
  ref: Pope.jpg
- title: Blended 7 Levels
  ref: blended_6_Beach.jpg
- title: Blended 11 Levels
  ref: blended_10_Beach.jpg

- title: Apple
  ref: apple.jpeg
- title: Orange
  ref: orange.jpeg
- title: Blended 5 Levels
  ref: blended_4_apple.jpeg
- title: Blended 10 Levels
  ref: blended_9_apple.jpeg

- title: Mars
  ref: Mars2.jpg
- title: Mask Zach
  ref: Mask-Zach.jpg
- title: Zach
  ref: Zach-puppy.jpg
- title: Blended 8 Levels
  ref: blended_8_Mars2.jpg


## P4 IMAGES ##


p4_path: 'images/p4/'


p4_stonehenge:
- title: 300 Horizontal Seams Shown
  ref: stonehenge/300h_seams_remove_stonehenge.jpg
  dimensions: [1600, 1067]
- title: 600 Vetical Seams Shown
  ref: stonehenge/600v_seams_remove_stonehenge.jpg
  dimensions: [1600, 1067]

- title:  300 Horizontal Seams Removed
  ref: stonehenge/scharr_300__0_stonehenge.jpg
  dimensions: [1600, 767]
- title: Y-Scaled to 767, X-Cropped
  ref: stonehenge/stonehenge-0-300.jpg
  dimensions: [1600, 767]

- title: 200 Vertical, 100 Horizontal Seams Removed
  ref: stonehenge/scharr_100__200_stonehenge.jpg
  dimensions: [1400, 967]
- title: Y-Scaled to 967px, X-Cropped
  ref: stonehenge/stonehenge-100-200.jpg
  dimensions: [1400, 967]


- title: 300 Vertical Seams Removed
  ref: stonehenge/scharr_300__600_stonehenge.jpg
  dimensions:  [1000, 767]
- title: Y-Scaled to 967px, X-Cropped
  ref: stonehenge/stonehenge-300-600.jpg
  dimensions:  [1000, 767]


p4_stonehenge_lightning:
- title: 100 Horizontal Seams Shown
  ref: stonehenge/100h_seams_remove_stonehenge-lightning.jpg
  dimensions: [1244, 800]
- title: 200  Vertical Seams Shown
  ref: stonehenge/200v_seams_remove_stonehenge-lightning.jpg
  dimensions:  [1244, 800]


- title: 300 Vertical, 300 Horizontal Seams Removal
  ref: stonehenge/scharr_300__300_stonehenge-lightning.jpg
  dimensions:  [944, 500]
- title:  X&Y-Cropped by 300px each
  ref: stonehenge/stonehenge-lightning-300-300-cropped.jpg
  dimensions:  [944, 500]
- title: X-Scaled to 994PX, Y-Cropped
  ref: stonehenge/stonehenge-lightning-scaled-croped-300-300.jpg
  dimensions: [944, 500]

p4_stonehenge_night:
- title:  100 Horizontal Seams Shown
  ref: stonehenge/100h_seams_remove_stonehenge-night.jpg
  dimensions: [620, 388]

- title: 200 Vertical Seams Shown
  ref: stonehenge/200v_seams_remove_stonehenge-night.jpg
  dimensions: [620, 388]

- title: Stonehenge Photo Collage
  ref: stonehenge/stonehenge-night-collage.jpg
  dimensions: [320, 388]

p4_stary:
- title: Starry Night Original
  ref: originals/staryNight.jpg

- title: 100 Horizontal Seams Shown
  ref: baseExamples/staryNight/100h_seams_remove_staryNight.jpg

- title: 100 Horizontal Seams Removed
  ref: baseExamples/staryNight/scharr_100__0_staryNight.jpg

- title: 200 Horizontal Seams Removed
  ref: baseExamples/staryNight/scharr_200__0_staryNight.jpg

- title: 300 Horizontal Seams Removed
  ref: baseExamples/staryNight/scharr_300__0_staryNight.jpg

- title: 455 Horizontal Seams Removed
  ref: baseExamples/staryNight/sobel_450__0_staryNight.jpg


p4_hw:
- title: 100 Horizontal Seams Added
  ref: baseExamples/hw/scharr_-100__0_homework.jpg
- title: 200 Horizontal Seams Shown
  ref: baseExamples/hw/200h_seams_remove_homework.jpg
- title: Original Image
  ref: originals/homework.jpg
- title: 200 Vertical Seams Shown
  ref: baseExamples/hw/200v_seams_remove_homework.jpg
- title: 200 Vertical Seams Added
  ref: baseExamples/hw/scharr_0__-200_homework.jpg
- title: 200 Vertical Seams Removed
  ref: baseExamples/hw/scharr_0__200_homework.jpg


p4_port:
- title: 100 Horizontal Seams Added
  ref: baseExamples/hw/scharr_-100__0_homework.jpg
- title: 200 Horizontal Seams Shown
  ref: baseExamples/hw/200h_seams_remove_homework.jpg
- title: Original Image
  ref: originals/homework.jpg
- title: 200 Vertical Seams Shown
  ref: baseExamples/hw/200v_seams_remove_homework.jpg
- title: 200 Vertical Seams Added
  ref: baseExamples/hw/scharr_0__-200_homework.jpg
- title: 200 Vertical Seams Removed
  ref: baseExamples/hw/scharr_0__200_homework.jpg



p4_pc:
- title: 100 Horizontal Seam Removal Display
  ref: specialExamples/pCompare/100hRemoval.jpg
- title: 100 Horizontal Seam Removal Results
  ref: specialExamples/pCompare/100hRemovalOutput.jpg
- title: 300 Vertical Seam Protected Removal Display
  ref: specialExamples/pCompare/300vRemoval.jpg
- title: 300 Vertical Seam Protected Removal Results
  ref: specialExamples/pCompare/300vRemovalOutput.jpg
- title: 300 Vertical Seam Directed Removal Display
  ref: specialExamples/pCompare/300vRemovalAnti.jpg
- title: 300 Vertical Seam Directed Removal Results
  ref: specialExamples/pCompare/300vRemovalAntiOutput.jpg




p4_general:






#'''
#scharr_250__250_fireworks.jpg
#250h_seams_remove_fireworks.jpg
#250v_seams_remove_fireworks.jpg
#scharr_200__-300_fireworks.jpg
#300v_seams_remove_fireworks.jpg
#200h_seams_remove_fireworks.jpg
#'''



## END OF P4 ##




eecs_images:
- title: Cathedral
  ref:  cathedral.jpg
- title: Tobolsk
  ref:  tobolsk.jpg
- title: Nativity
  ref:  nativity.jpg
- title: Settlers
  ref:  settlers.jpg
- title: Monastery
  ref:  monastery.jpg

extra_images:
- title: Bridge Over Ekaterininsko
  ref:  gamma_bridgeOverEkaterininskoe.jpg
- title: Chapel and Cross
  ref:  gamma_chapelAndCross.jpg
- title: Palace
  ref:  gamma_formerPalace.jpg
- title: Lava River
  ref:  gamma_lavaRiver.jpg
- title: Lava River and Boat
  ref:  gamma_lavaRiverAndBoat.jpg


images:
- title: Cathedral
  ref:  images/output/out_cathedral.jpg
  link: http://zzeleznick.github.io/cs194-fma/images/output/out_cathedral.jpg
  data:
  - size: "(1024, 390)"
    vector: "Green =  <2, -2>;  Red =   <6, -3>"
- title: Tobolsk
  ref:  images/output/out_tobolsk.jpg
  link: "http://zzeleznick.github.io/cs194-fma/images/output/out_tobolsk.jpg"
  data:
  - size: "(1024, 396)"
    vector: "Green =  <3, -4>;  Red =   <3, -7>"
- title: Nativity
  ref:  images/output/out_nativity.jpg
  link: http://zzeleznick.github.io/cs194-fma/images/output/out_nativity.jpg
  data:
  - size: "(1024, 395)"
    vector: "Green =  <1, -4>;  Red =   <0, -6>"
- title: Settlers
  ref:  images/output/out_settlers.jpg
  link: http://zzeleznick.github.io/cs194-fma/images/output/out_settlers.jpg
  data:
  - size: "(1024, 395)"
    vector: "Green = <0, 0>;  Red = <-1, 1>"
- title: Monastery
  ref:  images/output/out_monastery.jpg
  link: http://zzeleznick.github.io/cs194-fma/images/output/out_monastery.jpg
  data:
  - size: "(1024, 391)"
    vector: "Green = <2, -10>;  Red = <2, -11>"
- title: White-Balanced Monastery
  ref:  images/output/out_monastery.jpg
  link: http://zzeleznick.github.io/cs194-fma/images/output/out_monastery.jpg
  data:
  - size: "(1024, 391)[2]"
    vector: "Green = <2, -10>;  Red = <2, -11>"



# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
gems:      []

# Conversion
markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

quiet:    false
defaults: []

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style